config/routes.rb
require "sidekiq/web"
require "sidecloq/web"

Rails.application.routes.draw do
  if Rails.env.development?
    mount MailPreview => "mailers"
  end

  # Helpscout sidebar hook
  get "helpscout_hooks/show"
  post "/helpscout_hook", to: "helpscout_hooks#create", as: :helpscout_hook

  # Admin tools
  authenticate :user, ->(u) { u.is_admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  ActiveAdmin.routes(self)

  # Redirects for old paths
  get "/get-involved/team", to: redirect("/about/team")
  get "/get-involved/faq", to: redirect("/about/faq")
  get "/contact/press", to: redirect("/press")
  get "/contact/assets", to: redirect("about/assets")
  get "/assets", to: redirect("about/assets")
  get "/faq", to: redirect("/about/faq")
  get "/contact", to: redirect("/general_inquiries/new")

  get "/resources", to: redirect("/program")
  get "/about/ambassadors", to: redirect("/initiatives/ambassadors")
  get "/program/ambassadors", to: redirect("/initiatives/ambassadors")
  get "/about/clusters", to: redirect("/program/clusters")
  get "/about/previous", to: redirect("/program/previous")
  get "/about/tracks", to: redirect("/program/tracks")
  get "/about/youth", to: redirect("/initiatives/youth")
  get "/program/youth", to: redirect("/initiatives/youth")
  get "/panel-picker/mine", to: redirect("/dashboard")
  get "/voting/mine", to: redirect("/dashboard")
  get "/panel-picker", to: redirect("/voting")
  get "/panel-picker/search", to: redirect("/voting")
  get "/panel-picker/track", to: redirect("/voting")

  # Vanity redirects
  get "/live", to: redirect("https://dswlive.intelivideo.com/")
  get "/publishme", to: redirect("/get-involved/content")

  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions",
                                   passwords: "users/passwords"}

  resource :registration, only: %i[new create] do
    collection do
      get :closed
      get :confirm
    end
  end

  resources :submissions, except: [:destroy], path: "voting", path_names: {new: "submit"} do
    collection do
      get :thanks
      get :by_day
      get :feedback_closed
      get :faq
    end
    resources :votes, only: :create
    resources :comments, only: :create
  end

  resources :feedback, only: %i[new create]
  resources :venues, only: [:edit, :update]
  resources :venue_availabilities, except: [:destroy]

  resource :dashboard, only: :show

  resources :newsletter_signups, only: :create
  resources :general_inquiries, path: "general-inquiry", only: [:create, :new]
  resources :job_fair_signups, path: "job-fair-signups", only: [:create, :new]
  resources :sponsor_signups, only: :create

  resources :articles, except: [:destroy]

  scope :program do
    resources :clusters, only: :show, param: :name
    resources :tracks, only: :show, param: :name
  end

  get "/schedule", to: "schedules#index", as: :schedules
  get "/schedule/:year",
    to: "schedules#index",
    as: :schedules_by_year,
    constraints: {year: /\d{4}/},
    defaults: {year: Date.today.year}
  get "/schedule/:start_day",
    to: "schedules#by_day",
    as: :schedules_by_day,
    constraints: ->(r) { Submission::DAYS.invert.include?(r.params[:start_day].titleize) },
    defaults: {start_day: "monday", format: "html"}
  get "/schedule/:year/:start_day",
    to: "schedules#by_day",
    as: :schedules_by_year_by_day,
    constraints: ->(r) { Submission::DAYS.invert.include?(r.params[:start_day].titleize) && r.params[:year] =~ /\d{4}/ },
    defaults: {start_day: "monday", year: Date.today.year, format: "html"}
  get "/schedule/:id", to: "schedules#show", as: :schedule
  post "/schedule/:id", to: "schedules#create", as: :add_to_schedule
  delete "/schedule/:id", to: "schedules#destroy", as: :remove_from_schedule
  get "/schedule/:id/feed", to: "schedules#feed", as: :schedule_feed

  get "/register", to: "registrations#new", as: :register

  namespace :pitch_contest do
    resources :entries, only: :index do
      resources :votes, only: :create
    end
  end

  resource :company_search, only: %i[show] do
    collection do
      get :mine
    end
  end

  resource :user_search, only: %i[show]

  get "enable-simple-reg", to: "simple_registrations#enable", as: :enable_simple_reg
  get "disable-simple-reg", to: "simple_registrations#disable", as: :disable_simple_reg

  get "/(*page)", to: "site#index", as: :page, defaults: {page: :index}
  root to: "site#index"
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  respond_to :html
  rescue_from ActionView::MissingTemplate, with: :reraise_routing_error

  def index
    render template: page_partial
  end

  private

  def page_partial
    template_name = "site/#{params[:page].presence || "index"}".underscore
    lookup_context.find(template_name).virtual_path
  end

  def reraise_routing_error
    raise ActionController::RoutingError.new("Template not found")
  end
end

app/views/site/program/clusters.html.slim
- content_for(:title, 'Program')
- content_for(:subtitle, 'Clusters')
= render layout: 'layouts/shared/secondary_hero', locals: { title: 'Clusters', sub_title: 'Industry Deep Dives', description: "Denver Startup Week’s Clusters deep dive into the most exciting, relevant, and budding industries of the day. Cutting across our programming Tracks, the Clusters provide a different perspective on specific topics and themes throughout the week." } do
  = render 'layouts/shared/programs_secondary_hero_nav'

div.Tracks-list-wrapper
  = render 'components/content_card_list', attributes: { 'aria-label': "Clusters" }  do
    - Cluster.template_list_data.each do |card|
      = render 'components/content_card_list_item' do
        = render 'components/content_card', card: card, title: card[:title], page_url: "program/clusters/#{card[:slug] || card[:name].parameterize}"

app/views/site/program/previous.html.slim
= render partial: 'layouts/shared/program_nav', locals: { item: :previous }

section.common
  .section-content.sm-centered
    h6 = link_to 'EXPLORE PAST SCHEDULES', schedules_by_year_by_day_path(year: most_recent_past_year), class: 'btn-cta'

.section-content.sm-centered
  - Submission.with_slides_or_video.group_by(&:year).each do |year, submissions|
    h1 #{year} Slides &amp; Videos
    .list-flex-container
      - submissions.each do |submission|
        .list-item
          h6 = submission.title
          .list-icons
            - if submission.video_url.present?
              = link_to submission.video_url, target: '_blank' do
                = render partial: 'icons/triangle_right'
            - else
              a.disabled
                = render partial: 'icons/triangle_right'
            - if submission.slides_url.present?
              = link_to submission.slides_url, target: '_blank' do
                = render partial: 'icons/download'
            - else
              a.disabled
                = render partial: 'icons/download'

= render partial: 'layouts/shared/page_footer'

app/views/site/program/selection.html.slim
= render partial: 'layouts/shared/program_nav', locals: { item: :selection }
- content_for(:subtitle, 'Selection Process')

section.common.sm-centered
  .section-content
    h1 How the Selection Process Works
    h6 The Denver Startup Week community plays a critical role in creating the event’s programming. Each spring, Denver Startup Week opens a Call for Session Submissions process in which the community is asked to provide session submissions to put on during Denver Startup Week. After the session submissions are collected, they are all posted to the DSW website for public vote.  After the voting process concludes, the DSW Organizing Committee uses the vote totals to guide the final selections of sessions that are selected for inclusion in Denver Startup Week.
    h6 In 2017, nearly 1,200 sessions were proposed by the community, resulting in 376 individual sessions and events during Denver Startup Week. The DSW Organizing Committee works tirelessly to ensure that Denver Startup Week offers world-class programming that reflects the diverse expertise of Denver's innovation community and serve up a little something for everyone.

section.common.sm-centered
  .section-content
    h1 Key Dates for #{AnnualSchedule.current.year}
    = render partial: 'layouts/shared/schedule'

section.common.sm-centered
  .section-content
    h1 TIPS & TRICKS FOR SUBMITTING GREAT SESSIONS
    h6 What kind of ideas have the best chance of being selected?
    h6 All types of sessions are welcome! In the past, individual or group presentations, panels, and workshops have all worked quite well. Ideas focused on transferring knowledge to the community have the best chance of being selected, and we will give particular consideration to those that are unique, new, or different.

    h6 Pitches for a specific company, product, or service will not be accepted.

    h6 What are the selection criteria for submissions?
    h6 We're primarily looking for sessions that embody the goals and values of the week, provide real value to attendees, and promote the local community. We use a number of different criteria to evaluate sessions, including the appropriateness of the session to the goals of the week, the quality and thoughtfulness of the session description and speaker(s), the results of the public voting/commenting period, the overall balance of content for the week, the overall balance of speakers/companies represented during the week, and other factors.
    h6 We also tend to get many session proposals covering similar topics. In those cases, we may either pick representative sessions or try to combine multiple sessions into a single panel. However, in many of these cases we do feel that it is important to open up the schedule to different speakers and topics than we’ve had in previous years in order to expand our audience and subject areas.

    h6 Can I Submit Multiple Sessions?
    h6 We welcome up to 3 sessions submissions per person.  That being said, we highly recommend that any session that you submit represents your best effort to create the best session possible.  Denver Startup Week loves quality over quantity.

    h6 TIPS & TRICKS FOR SUBMITTING GREAT SESSIONS
    h6 For more Tips & Tricks, read DSW BLOG ON TIPS & TRICKS / PODCAST TBD

    h6
      | Looking for examples of past sessions?  Check out the 
      = most_recent_past_year
      |  Denver Startup Week schedule
      = link_to ' here', schedules_by_year_by_day_path(year: most_recent_past_year)
      |.

section.common.sm-centered
  .section-content
    h1 READY TO SUBMIT A SESSION?
    h6 The Call for Session Submissions will be open #{AnnualSchedule.current.cfp_open_at.try(:to_s, :month_day) || 'TBD'} - #{AnnualSchedule.current.cfp_close_at.try(:to_s, :month_day) || 'TBD'}! We’ll share more details soon through our newsletter and social media channels. In the meantime, get working on putting together a stellar program to engage, educate, and inspire our community of innovators.

app/views/site/program/tracks.html.slim
- content_for(:title, 'Program')
- content_for(:subtitle, 'Tracks')
= render layout: 'layouts/shared/secondary_hero', locals: { title: 'Tracks', sub_title: 'ORGANIZE YOUR WEEK USING THE DENVER STARTUP WEEK TRACKS', description: "The sessions throughout the annual event are organized into eight tracks that are oriented around key functional roles within a business. Whether a company founder, marketer, artist, sales specialist, developer, manufacturer, or anything in between - Denver Startup Week has something for you." } do
  = render 'layouts/shared/programs_secondary_hero_nav'

div.Tracks-list-wrapper
  = render 'components/content_card_list', attributes: { 'aria-label': "Tracks" } do
    - Track.template_list_data.each do |card|
      = render 'components/content_card_list_item' do
        = render 'components/content_card', card: card, title: card[:title], page_url: "program/tracks/#{card[:track]}"