config/routes.rb
require "sidekiq/web"
require "sidecloq/web"

Rails.application.routes.draw do
  if Rails.env.development?
    mount MailPreview => "mailers"
  end

  # Helpscout sidebar hook
  get "helpscout_hooks/show"
  post "/helpscout_hook", to: "helpscout_hooks#create", as: :helpscout_hook

  # Admin tools
  authenticate :user, ->(u) { u.is_admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  ActiveAdmin.routes(self)

  # Redirects for old paths
  get "/get-involved/team", to: redirect("/about/team")
  get "/get-involved/faq", to: redirect("/about/faq")
  get "/contact/press", to: redirect("/press")
  get "/contact/assets", to: redirect("about/assets")
  get "/assets", to: redirect("about/assets")
  get "/faq", to: redirect("/about/faq")
  get "/contact", to: redirect("/general_inquiries/new")

  get "/resources", to: redirect("/program")
  get "/about/ambassadors", to: redirect("/initiatives/ambassadors")
  get "/program/ambassadors", to: redirect("/initiatives/ambassadors")
  get "/about/clusters", to: redirect("/program/clusters")
  get "/about/previous", to: redirect("/program/previous")
  get "/about/tracks", to: redirect("/program/tracks")
  get "/about/youth", to: redirect("/initiatives/youth")
  get "/program/youth", to: redirect("/initiatives/youth")
  get "/panel-picker/mine", to: redirect("/dashboard")
  get "/voting/mine", to: redirect("/dashboard")
  get "/panel-picker", to: redirect("/voting")
  get "/panel-picker/search", to: redirect("/voting")
  get "/panel-picker/track", to: redirect("/voting")

  # Vanity redirects
  get "/live", to: redirect("https://dswlive.intelivideo.com/")
  get "/publishme", to: redirect("/get-involved/content")

  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions",
                                   passwords: "users/passwords"}

  resource :registration, only: %i[new create] do
    collection do
      get :closed
      get :confirm
    end
  end

  resources :submissions, except: [:destroy], path: "voting", path_names: {new: "submit"} do
    collection do
      get :thanks
      get :by_day
      get :feedback_closed
      get :faq
    end
    resources :votes, only: :create
    resources :comments, only: :create
  end

  resources :feedback, only: %i[new create]
  resources :venues, only: [:edit, :update]
  resources :venue_availabilities, except: [:destroy]

  resource :dashboard, only: :show

  resources :newsletter_signups, only: :create
  resources :general_inquiries, path: "general-inquiry", only: [:create, :new]
  resources :job_fair_signups, path: "job-fair-signups", only: [:create, :new]
  resources :sponsor_signups, only: :create

  resources :articles, except: [:destroy]

  scope :program do
    resources :clusters, only: :show, param: :name
    resources :tracks, only: :show, param: :name
  end

  get "/schedule", to: "schedules#index", as: :schedules
  get "/schedule/:year",
    to: "schedules#index",
    as: :schedules_by_year,
    constraints: {year: /\d{4}/},
    defaults: {year: Date.today.year}
  get "/schedule/:start_day",
    to: "schedules#by_day",
    as: :schedules_by_day,
    constraints: ->(r) { Submission::DAYS.invert.include?(r.params[:start_day].titleize) },
    defaults: {start_day: "monday", format: "html"}
  get "/schedule/:year/:start_day",
    to: "schedules#by_day",
    as: :schedules_by_year_by_day,
    constraints: ->(r) { Submission::DAYS.invert.include?(r.params[:start_day].titleize) && r.params[:year] =~ /\d{4}/ },
    defaults: {start_day: "monday", year: Date.today.year, format: "html"}
  get "/schedule/:id", to: "schedules#show", as: :schedule
  post "/schedule/:id", to: "schedules#create", as: :add_to_schedule
  delete "/schedule/:id", to: "schedules#destroy", as: :remove_from_schedule
  get "/schedule/:id/feed", to: "schedules#feed", as: :schedule_feed

  get "/register", to: "registrations#new", as: :register

  namespace :pitch_contest do
    resources :entries, only: :index do
      resources :votes, only: :create
    end
  end

  resource :company_search, only: %i[show] do
    collection do
      get :mine
    end
  end

  resource :user_search, only: %i[show]

  get "enable-simple-reg", to: "simple_registrations#enable", as: :enable_simple_reg
  get "disable-simple-reg", to: "simple_registrations#disable", as: :disable_simple_reg

  get "/(*page)", to: "site#index", as: :page, defaults: {page: :index}
  root to: "site#index"
end

app/views/layouts/shared/_about_secondary_hero_nav.html.slim
= render 'components/secondary_hero_nav', routes: about_routes, nav_title: 'about'

app/views/layouts/shared/_auth_nav.html.slim
nav.section-nav
  .section-content
    h1 My Account
    = link_to 'Sign in', new_user_session_path, class: current_page?(new_user_session_path) ? 'active' : ''
    = link_to 'Create an account', new_user_registration_path, class: current_page?(new_user_registration_path) ? 'active' : ''
    = link_to 'Reset your password', new_password_path(resource_name), class: current_page?(new_password_path(resource_name)) ? 'active' : ''

section.common.green
  .section-content.sm-centered
    - if flash.empty?
      h6 You need an account to register, vote, or submit sessions. Please sign in or create one.
    - flash.each do |key, message|
      h6 = message
    - unless resource.errors.empty?
      h6 = "Please correct the following errors: #{resource.errors.full_messages.to_sentence}"

app/views/layouts/shared/_coc_acknowledgement.html.slim
.COCAcknowledgement
  = f.check_box :coc_acknowledgement, required: 'required', class: 'COCAcknowledgement-checkbox'
  = f.label :coc_acknowledgement, class: 'COCAcknowledgement-label' do
    span I have read and agree to be bound by the
    = link_to ' Denver Startup Week Code of Conduct.', page_path(page: 'code-of-conduct'), target: '_blank', class: 'COCAcknowledgement-link'

app/views/layouts/shared/_featured.html.slim
section.Featured
  .Featured-triangles
    .Featured-background-triangle--primary
    .Featured-background-triangle--secondary
  h2.Featured-header#Featured-header-id Featured Sessions & Articles
  div.Featured-list
    = render 'components/three_card_list', attributes: { 'aria-labeledby': 'Featured-header-id' } do
      = render 'layouts/shared/publishings_list_items', list: Publishing.for_homepage

app/views/layouts/shared/_footer.html.slim
= render layout: 'layouts/shared/layout_wrapper' do
  footer.Footer
    - unless content_for(:hide_footer_callouts)
      .Footer-primary-callouts
        = render partial: 'layouts/shared/primary_callouts_nav'
    .Footer-blocks
      .Footer-block
        .Footer-title Denver Startup Week #{Date.today.year}
        .Footer-subtitle &copy;Copyright #{Date.today.year}. All rights reserved.
        = render 'components/social_media_nav'
        = render 'layouts/shared/footer_nav', routes: footer_nav_routes, nav_title: "Footer"

      .Footer-block
        .Footer-updates 
          p.Footer-updates-title Stay in Touch
          = form_for NewsletterSignup.new, html: { data: { bindable: "newsletter-signup" } } do |f|
            = render layout: 'components/floating_input' do
              = f.text_field :email, required: 'required'
              = f.label :email, "Email Address"
            = f.submit 'Get Updates', class: "Footer-updates-submit"

    .Footer-sponsors
      .Footer-sponsors-block
        p UX/UI/Design System:
        a(href="https://www.guice.works/" aria-label="Guiceworks Website" target="_blank")
          img src="#{image_url('redesign/sponsors/guiceworks.svg')}"
      .Footer-sponsors-block
        p Engineering:
        a(href="https://skookum.com/" aria-label="Skookum Website" target="_blank")
          img src="#{image_url('redesign/sponsors/skookum.svg')}"

app/views/layouts/shared/_footer_nav.html.slim
nav.FooterNav(aria-label="#{nav_title} nav")
  ul.FooterNav-page-links-list
    - routes.each do |route|
      li(class="FooterNav-item")
        = link_to route[:label], route[:path]

app/views/layouts/shared/_fullscreen_takeover_header.html.slim
- close_action = request.fullpath == session[:previous_url] ? (request.referer || '/') : (session[:previous_url] || '/')
header.FullscreenTakeoverHeader(class="is-#{background}")
  = render layout: 'layouts/shared/layout_wrapper' do
    .FullscreenTakeoverHeader-inner
      h1.FullscreenTakeoverHeader-title #{title}
      a.FullscreenTakeoverHeader-link(href="#{close_action}", aria-label="back to home page")
        = render partial: 'icons/close'

app/views/layouts/shared/_initiatives_nav.html.slim
- content_for :title, 'Initiatives'

nav.section-nav
  .section-content
    h1 Initiatives
    = link_to 'Overview', page_path(page: 'initiatives'), class: item == :overview ? 'active' : ''
    = link_to 'Ambassadors', page_path(page: 'initiatives/ambassadors'), class: item == :ambassadors ? 'active' : ''
    = link_to 'Youth', page_path(page: 'initiatives/youth'), class: item == :youth ? 'active' : ''

app/views/layouts/shared/_layout_wrapper.html.slim
.LayoutWrapper
  = yield

app/views/layouts/shared/_publishings_list_items.html.slim
- list.each do |list_item|
  - if list_item[:subject_type] == 'Submission'
    = render 'components/three_card_list_item' do
      = render 'components/session_card', session: list_item.subject
  - if list_item[:subject_type] == 'Article'
    = render 'components/three_card_list_item' do
      = render 'components/article_card', article: list_item.subject

app/views/layouts/shared/_secondary_hero.html.slim
.SecondaryHero
  .SecondaryHero-inner
    .SecondaryHero-sub-title #{sub_title}
    - if description.kind_of?(Array)
      - description.each do |desc|
        .SecondaryHero-description #{desc}
    - else
      .SecondaryHero-description #{description}
    .SecondaryHero-title #{title}

    .SecondaryHero-extras
      = yield

app/views/layouts/shared/_similar_resources_list.html.slim
.SimilarResourcesList
  h2.SimilarResourcesList-title You may also be interested in
  .SimilarResourcesList-list
    = render 'components/three_card_list', attributes: { 'aria-label': "similar resources" } do
      - resources.each do |resource|
        = render 'components/three_card_list_item' do
          = render 'components/resource_card', resource: resource

app/views/layouts/shared/_sponsorship.html.slim
.sponsor-container
  a.sponsor-logo href="#{sponsorship.link_href}" target='_blank' title="#{sponsorship.name}"
    = image_tag sponsorship.logo.url, alt: sponsorship.name
  .sponsor-copy
    - if sponsorship.track.present?
      div(class="sponsor-track #{sponsorship.track.color}")
        = render partial: "icons/#{sponsorship.track.icon}"
        span = sponsorship.track.name
    - if sponsorship.submission.present?
      div(class="sponsor-track #{sponsorship.submission.track.color}")
        = render partial: "icons/#{sponsorship.submission.track.icon}"
        span = link_to sponsorship.submission.title, schedule_path(sponsorship.submission)
    span = sponsorship.description

app/views/layouts/shared/_sub_program_details_hero.html.slim
.SubProgramDetailsHero(class="#{color}-background")
  .SubProgramDetailsHero-inner
    a(href="#{back_url}" aria-label="Back to Previous" style="fill: white" class="SubProgramDetailsHero-back-btn")
      = render partial: 'icons/arrow_in_circle_left'
      .SubProgramDetailsHero-back-text Back to #{sub_program}
    - if local_assigns[:desc].present? && !came_from_program_tracks?
      .SubProgramDetailsHero-desc(class="#{color}-font-on-#{color}") #{desc}
    .SubProgramDetailsHero-title-wapper
      .SubProgramDetailsHero-title(class="#{color}-font-on-#{color}") #{title}
      = link_to "View #{title} Sessions", schedules_path(filter: "#{title}"), class:"#{color}-font-on-#{color} #{color}-border-on-#{color}-background SubProgramDetailsHero-SubProgram-btn"