config/routes.rb
require "sidekiq/web"
require "sidecloq/web"

Rails.application.routes.draw do
  if Rails.env.development?
    mount MailPreview => "mailers"
  end

  # Helpscout sidebar hook
  get "helpscout_hooks/show"
  post "/helpscout_hook", to: "helpscout_hooks#create", as: :helpscout_hook

  # Admin tools
  authenticate :user, ->(u) { u.is_admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  ActiveAdmin.routes(self)

  # Redirects for old paths
  get "/get-involved/team", to: redirect("/about/team")
  get "/get-involved/faq", to: redirect("/about/faq")
  get "/contact/press", to: redirect("/press")
  get "/contact/assets", to: redirect("about/assets")
  get "/assets", to: redirect("about/assets")
  get "/faq", to: redirect("/about/faq")
  get "/contact", to: redirect("/general_inquiries/new")

  get "/resources", to: redirect("/program")
  get "/about/ambassadors", to: redirect("/initiatives/ambassadors")
  get "/program/ambassadors", to: redirect("/initiatives/ambassadors")
  get "/about/clusters", to: redirect("/program/clusters")
  get "/about/previous", to: redirect("/program/previous")
  get "/about/tracks", to: redirect("/program/tracks")
  get "/about/youth", to: redirect("/initiatives/youth")
  get "/program/youth", to: redirect("/initiatives/youth")
  get "/panel-picker/mine", to: redirect("/dashboard")
  get "/voting/mine", to: redirect("/dashboard")
  get "/panel-picker", to: redirect("/voting")
  get "/panel-picker/search", to: redirect("/voting")
  get "/panel-picker/track", to: redirect("/voting")

  # Vanity redirects
  get "/live", to: redirect("https://dswlive.intelivideo.com/")
  get "/publishme", to: redirect("/get-involved/content")

  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions",
                                   passwords: "users/passwords"}

  resource :registration, only: %i[new create] do
    collection do
      get :closed
      get :confirm
    end
  end

  resources :submissions, except: [:destroy], path: "voting", path_names: {new: "submit"} do
    collection do
      get :thanks
      get :by_day
      get :feedback_closed
      get :faq
    end
    resources :votes, only: :create
    resources :comments, only: :create
  end

  resources :feedback, only: %i[new create]
  resources :venues, only: [:edit, :update]
  resources :venue_availabilities, except: [:destroy]

  resource :dashboard, only: :show

  resources :newsletter_signups, only: :create
  resources :general_inquiries, path: "general-inquiry", only: [:create, :new]
  resources :job_fair_signups, path: "job-fair-signups", only: [:create, :new]
  resources :sponsor_signups, only: :create

  resources :articles, except: [:destroy]

  scope :program do
    resources :clusters, only: :show, param: :name
    resources :tracks, only: :show, param: :name
  end

  get "/schedule", to: "schedules#index", as: :schedules
  get "/schedule/:year",
    to: "schedules#index",
    as: :schedules_by_year,
    constraints: {year: /\d{4}/},
    defaults: {year: Date.today.year}
  get "/schedule/:start_day",
    to: "schedules#by_day",
    as: :schedules_by_day,
    constraints: ->(r) { Submission::DAYS.invert.include?(r.params[:start_day].titleize) },
    defaults: {start_day: "monday", format: "html"}
  get "/schedule/:year/:start_day",
    to: "schedules#by_day",
    as: :schedules_by_year_by_day,
    constraints: ->(r) { Submission::DAYS.invert.include?(r.params[:start_day].titleize) && r.params[:year] =~ /\d{4}/ },
    defaults: {start_day: "monday", year: Date.today.year, format: "html"}
  get "/schedule/:id", to: "schedules#show", as: :schedule
  post "/schedule/:id", to: "schedules#create", as: :add_to_schedule
  delete "/schedule/:id", to: "schedules#destroy", as: :remove_from_schedule
  get "/schedule/:id/feed", to: "schedules#feed", as: :schedule_feed

  get "/register", to: "registrations#new", as: :register

  namespace :pitch_contest do
    resources :entries, only: :index do
      resources :votes, only: :create
    end
  end

  resource :company_search, only: %i[show] do
    collection do
      get :mine
    end
  end

  resource :user_search, only: %i[show]

  get "enable-simple-reg", to: "simple_registrations#enable", as: :enable_simple_reg
  get "disable-simple-reg", to: "simple_registrations#disable", as: :disable_simple_reg

  get "/(*page)", to: "site#index", as: :page, defaults: {page: :index}
  root to: "site#index"
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  respond_to :html
  respond_to :json, only: :index
  respond_to :ics, only: :index

  before_action :ensure_registered!, only: %i[create destroy]
  before_action :authenticate_user!, only: %i[create destroy]

  def index
    @sessions = Submission
      .for_year(params[:year])
      .for_schedule
      .order(:start_day)
      .includes(:venue,
        :submitter,
        :track,
        :cluster,
        sponsorship: :track)
    respond_to do |format|
      format.html do
        redirect_to schedules_by_year_by_day_path({year: current_year_or_default, start_day: current_day_or_default}.merge(request.query_parameters))
      end
      format.json do
        respond_with @sessions
      end
    end
  end

  def by_day
    @day_index = Submission::DAYS.invert[params[:start_day].titleize]
    @sessions = Submission
      .for_year(params[:year])
      .for_schedule
      .for_start_day(params[:start_day])
      .for_schedule_filter(params[:filter], current_user)
      .fulltext_search(params[:terms])
      .order(:start_hour)
      .includes(:venue,
        :submitter,
        :track,
        :cluster,
        sponsorship: :track)
    respond_with @sessions
  end

  def show
    @session = Submission
      .for_schedule
      .where(id: params[:id].to_i)
      .order(:start_day)
      .includes(:venue,
        :track,
        :cluster,
        :presenters,
        sponsorship: :track)
      .first!

    @related_sessions = @session
      .cached_similar_items
      .for_schedule
      .limit(3)
      .includes(:venue,
        :track,
        :cluster,
        sponsorship: :track)
  end

  def feed
    registration = Registration.where(calendar_token: params[:id]).includes(:user).first!
    @sessions = registration
      .submissions.for_current_year
      .for_schedule
      .order("created_at asc")
      .includes(:venue,
        :submitter,
        :track,
        :cluster,
        sponsorship: :track)
    if stale?(@sessions)
      respond_to do |format|
        format.ics do
          render body: to_calendar(registration, @sessions).to_ical, media_type: "text/calendar"
        end
      end
    end
  end

  def create
    @session = Submission
      .for_schedule
      .where(id: params[:id].to_i)
      .first!
    current_registration.submissions << @session unless current_registration.submissions.include?(@session)
    redirect_to schedule_path(@session)
  end

  def destroy
    @session = Submission
      .for_schedule
      .where(id: params[:id].to_i)
      .first!
    current_registration.session_registrations.where(submission_id: @session.id).destroy_all
    redirect_to schedule_path(@session)
  end

  private

  def current_day_or_default
    if AnnualSchedule.in_week?
      zone = ActiveSupport::TimeZone["America/Denver"]
      day_index = ((zone.now.at_beginning_of_day - AnnualSchedule.current.week_start_at.at_beginning_of_day.in_time_zone(zone)) / 1.day).ceil + 1
      Submission::DAYS[day_index].downcase
    else
      "monday"
    end
  end

  helper_method :current_day_or_default

  def current_year_or_default
    if params[:year].present?
      params[:year]
    elsif AnnualSchedule.registration_open? || AnnualSchedule.post_week?
      Date.today.year
    else
      Date.today.year - 1
    end
  end

  helper_method :current_year_or_default

  def to_calendar(registration, sessions)
    Icalendar::Calendar.new.tap do |calendar|
      calendar.x_wr_calname = "#{registration.user.name}'s Denver Startup Week #{Date.today.year} Schedule"
      sessions.each do |submission|
        url = schedule_url(submission)
        event_start = submission.start_datetime
        event_end = submission.end_datetime
        tzid = submission.start_datetime.time_zone.tzinfo.identifier
        tz = TZInfo::Timezone.get(tzid)
        timezone = tz.ical_timezone(event_start)
        calendar.add_timezone(timezone)
        event = Icalendar::Event.new.tap do |e|
          e.dtstart       = Icalendar::Values::DateTime.new(event_start, "tzid" => tzid)
          e.dtend         = Icalendar::Values::DateTime.new(event_end, "tzid" => tzid)
          e.summary       = submission.full_title
          e.description   = "#{submission.description}\n\nMore details: #{url}"
          e.location      = submission.ical_location
          e.ip_class      = "PUBLIC"
          e.created       = submission.created_at
          e.last_modified = submission.updated_at
          e.uid           = url
          e.url           = url
        end
        calendar.add_event(event)
      end
      calendar.publish
    end
  end
end

app/helpers/schedule_helper.rb
module ScheduleHelper

  def formatted_start_date_for_index(index, year, format = '%B %-d')
    (AnnualSchedule.find_by!(year: year).week_start_at + index - 2).strftime(format)
  end

  def registered_for_session?(submission)
    registered? && current_registration.submission_ids.include?(submission.id)
  end

  def ratings_for_select
    Feedback::RATINGS.invert
  end

  def in_or_post_week?
    AnnualSchedule.in_week? || AnnualSchedule.post_week?
  end

end

app/views/schedules/_feedback_form.html.slim
section.SessionFeedback
  h1 Share Feedback
  = form_for @session.feedback.build do |f|
    = render layout: 'components/floating_input' do
      = f.select :rating, ratings_for_select, { :include_blank => '' }, required: 'required'
      = f.label :rating, 'Please rate this session'
    = render layout: 'components/floating_input' do
      = f.text_field :comments
      = f.label :comments, 'Comments'
    = f.hidden_field :submission_id, value: @session.id
    = f.submit 'Share Feedback', class: "SessionFeedback-submit"

app/views/schedules/by_day.html.slim
- content_for(:title, "#{formatted_start_date_for_index(@day_index, current_year_or_default, '%A %B %-d, %Y')} Schedule")
- title = (current_year_or_default.to_i == Date.today.year) ? "Schedule" : "#{current_year_or_default} Schedule"

= render layout: 'layouts/shared/secondary_hero', locals: { title: title, sub_title: 'SOMETHING FOR EVERYONE', description: 'Dive into the Denver Startup Week schedule for sessions, keynotes, workshops, celebrations, and much more. With over 300 free events, there is something for everyone to learn, grow, and be inspired. Don’t forget to register, RSVP for individual sessions, and remember that seating is first come, first served.' } do
  form.Schedule-form
    .Schedule-search
      = render partial: 'components/search', locals: { placeholder: ''}
    .Schedule-filters
      .Schedule-filter
        = render layout: 'components/dropdown', locals: { name: "filter",  onchange: "this.form.submit();", value: params[:filter] } do
          option(value="all" selected=("selected" if params[:filter] == 'all')) View All Sessions
          option(value="mine" selected=("selected" if params[:filter] == 'mine')) View My Schedule
          optgroup(label="View Sessions by Track")
            - Track.dropdown_options.each do |opt|
              option(value="#{opt.value}" selected=("selected" if params[:filter] == opt.value)) #{opt.label}#{opt.is_submittable? ? ' Track' : '' }
          optgroup(label="View Sessions by Cluster")
            - Cluster.dropdown_options.each do |opt|
              option(value="#{opt.value}" selected=("selected" if params[:filter] == opt.value)) #{opt.label} Cluster
      .Schedule-filter
        = render layout: 'components/dropdown', locals: { name: "year", onchange: "window.location.href = this.form.elements[2].value;", value: params[:year] } do
          optgroup(label="View Sessions by Year")
          = Submission.distinct.order('year DESC').pluck(:year).each do |y|
            option(value="#{schedules_by_year_by_day_path(y, current_day_or_default)}" selected=("selected" if params[:year] == y.to_s)) = y

= render layout: 'layouts/shared/layout_wrapper' do
  nav.Schedule-nav(aria-label="Schedule Days")
    ul.Schedule-nav-list
      - Submission::DAYS.each do |index, day|
        li.Schedule-nav-list-item
          = link_to schedules_by_year_by_day_path(current_year_or_default, Submission::DAYS[index].downcase, request.query_parameters), class: "Schedule-nav-link #{@day_index == index ? 'is-active' : ''}" do
            .Schedule-nav-month = formatted_start_date_for_index(index, current_year_or_default, '%b')
            .Schedule-nav-day = formatted_start_date_for_index(index, current_year_or_default, '%-d')
            .Schedule-nav-weekday = formatted_start_date_for_index(index, current_year_or_default, '%A')
            - if @day_index == index
              img.Schedule-nav-arrow src="#{image_url('redesign/arrow-select-grey.svg')}"

  section.Schedule-lists
    - cache [ @sessions.maximum(:updated_at), @sessions.map(&:id) ] do
      - @sessions.group_by { |s| s.start_hour.floor }.each do |start_hour, grouping|
        h3.Schedule-list-time = grouping.first.human_start_time
        ul.Schedule-list(aria-label="#{grouping.first.human_start_time} Sessions")
          - grouping.each do |group|
              li.Schedule-list-item
                = render partial: 'components/scheduled_session', locals: { submission: group }

      - if @sessions.empty?
        .Schedule-empty-message We couldn't find any sessions! Please try a different filter or search criteria.

app/views/schedules/show.html.slim
- content_for(:title, @session.year)
- content_for(:subtitle, @session.full_title)
- content_for(:extra_meta_tags) do
  meta(property="og:title" content="Denver Startup Week | #{@session.full_title}")
  meta(property="og:site_name" content="Denver Startup Week")
  meta(property="og:url" content="#{schedule_url(@session)}")
  meta(property="og:description" content="#{truncate(@session.description, length: 300, separator: ' ')}")
  meta(name="date" content="#{@session.start_datetime.iso8601}")
  - if @session.noindex?
    meta(name="robots" content="noindex")
  script(type="application/ld+json") = session_ld_json(@session).html_safe

= render layout: 'layouts/shared/layout_wrapper' do
  - unless @session.current_year?
    .SessionDetail-prev-year-header
      h1.SessionDetail-title #{@session.year} Schedule


  section.SessionDetail-back-section
    = link_to back_to_path('schedule', schedules_by_year_by_day_path(year: @session.year, start_day:  @session.human_start_day.downcase)), class: 'SessionDetail-back-link' do
      .SessionDetail-back-icon
        = render partial: 'icons/arrow_in_circle_left'
      = "Back to #{back_to_label('schedule')}"

  section.SessionDetail
    header(class="SessionDetail-track #{@session.track.color}-font #{@session.track.color}-fill")
      - if @session.track.icon
        = render partial: "icons/#{@session.track.icon}"
      p = @session.track.name
    .SessionDetail-stats-container
      .SessionDetail-date #{@session.human_start_day}, #{@session.start_datetime.strftime('%-b %-d')}
      .SessionDetail-time #{@session.human_time_range}
      .SessionDetail-attendee-count = "#{@session.registrant_count} attending"
    .SessionDetail-columns
      .SessionDetail-column--left
        h1.SessionDetail-title = @session.full_title
        .SessionDetail-description = process_with_pipeline(@session.description)
        - if @session.presenters.any?
          .SessionDetail-presenters
            - @session.presenters.each do |presenter|
              .SessionDetail-presenter
                = render partial: 'components/name_with_avatar', locals: { user: presenter, name: presenter.name, align: 'right', color: 'grey' }

        - if @session.live_stream_url.present?
          a.SessionDetail-stream href='#'
            = render partial: 'icons/eyeball'
            span.SessionDetail-stream-label Watch it
            .SessionDetail-stream-details
              iframe(src="#{@session.live_stream_url}" frameborder="0" scrolling="no" allowfullscreen="" webkitallowfullscreen="" mozallowfullscreen="" oallowfullscreen="" msallowfullscreen="" width="100%" height="100%")

        - if @session.venue_confirmed?
          .SessionDetail-location
            p = @session.venue.name
            p = @session.venue.short_address
        - else
          .SessionDetail-location
            p = @session.human_location_name
        - if @session.has_childcare?
          a(href="https://www.nanno.com/event_forms/dsw-registration" class="SessionDetail-childcare-button" target="_blank")

        - if AnnualSchedule.registration_open? && @session.current_year?
          - if !registered? || !registered_for_session?(@session)
            = link_to 'Add to Schedule', add_to_schedule_path(@session), method: :post, class: 'SessionDetail-schedule-button'
          - else
            = link_to 'Remove from Schedule', remove_from_schedule_path(@session), method: :delete, class: 'SessionDetail-schedule-button SessionDetail-schedule-button--remove'


        - if @session.venue_confirmed?
          .SessionDetail-map(id="location_map" data-bindable="mapquest-map" data-name="#{@session.venue.name}" data-address="#{@session.venue.address_for_maps}")

        - if @related_sessions.any?
          h2.SessionDetail-title You may also be interested in
          ul.SessionDetail-related-sessions
            - @related_sessions.each do |submission|
              li.SessionDetail-related-session
                = render partial: 'components/scheduled_session', locals: { submission: submission, include_day: true }
      .SessionDetail-column--right
        - if user_signed_in?
          - registrants = @session.public_registrants(current_user)
          - cache [registrants.size, registrants.maximum(:updated_at)] do
            - registrants.each do |user|
              .SessionDetail-attendee
                = render partial: 'components/name_with_avatar', locals: { user: user, name: user.abbreviated_name, align: 'right', color: 'gray' }
                - if user[:linkedin_url].present?
                  = render partial: 'components/user_linkedin', locals: { user: user }

  - if user_signed_in? && @session.open_for_feedback?
    = render partial: 'feedback_form'